services:
  api:
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile.prod
    container_name: security-sample-api
    ports:
      - "5050:5050"
    environment:
      - NODE_ENV=prod
      - PORT=5050
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}          
    restart: always
    